### ISSUE TITLE
Internationalitzation

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#207]
The system should be available for Schools in different countries. Which means it should also have multi-language support.
The ability to save the selected language value is already being integrated in #156. 

In this task we need to enable CodeIgnitor Multi Language module and replace all labels/placeholders in the system with ability to translate them in 1 single file

**Comment by regiscamimura** [comment]
I've got the base for internationalization done. The usage is not the native CodeIgniter syntax, I added a function to pass the output through a custom translate function, so that will save a lot of time while changing the views to use the language.

In the views, we can use double curly braces whenever we want to use translation. For example: 

<h1>{{School Name}}</h1>

The function will automatically fetch anything inside the double curly braces and will apply the proper translation. If no translation is found for the word/term between the curly braces, then the curly braces will be removed and the plain text inside the curly brace will be displayed instead. That's also better than just displaying an empty string if no translation is found (which is CodeIgniter native library behavior).

To create the actual translate files, you need to go to ./application/language/[language dir]/easol_lang.php and add arrays entries there. For example, if we want to have {{School Name}} translated to portugues, we would do that:

1. Create a dir and a file for ./application/language/portuguese/easol_lang.php (if it doesn't exists yet)
2. Add this to that file:
$lang["School Name"] = "Nome da Escola";

Also, I did in a such way that it is case insensite, so you can $lang["School Name"] or $lang["school name"] or yet $lang["school_name"]. The same for the view, it can be {{School Name}} or {{School_name}} or any other combination. Our library will lowercase the keys and replace an empty space with an underscore if needed. That's just so we can use prefix or any other naming convention in the future, if we get to get clashing words and duplicated language keys.

I also added 3 filters to help out with string format. We can do {{School Name | lowercase }}, {{ School Name | uppercase }} or {{ School Name | capitalize }}, so the translated string will get the proper formatting. We have room to expand those filters in the future, including date formatting, money formatting, etc, FYI.

If we want to translate a single line we can also do <?php echo lang("School Name"); ?>. Filters are available as well, and it is also case insensitive. Useful for translating strings that are set in the controllers.

====

In the system management > language section, the dropdown box is now dynamic. The options will be set by reading the ./application/language directory, and will present all directories as options, but the directory MUST HAVE a easol_lang.php file.

Finally, note that despite the need of having an easol_lang.php file inside the language dir, we don't necessarily need to put all the translation in a single file. We can create a school_lang.php, a report_lang.php, sections_lang.php. Those are going to be loaded automatically, and we can use that separation if we want to organize the translation files and relate them to different sections of the system. 

Note that CodeIgniter already uses that separation of files, and we have public repositories of translated portions of CodeIgniter: https://github.com/bcit-ci/codeigniter3-translations/tree/develop/language

That's useful for form validation and other features that comes with CodeIgniter, and we just need to drop those files in the proper directory.

**Comment by regiscamimura** [comment]
It's pushed to the "207" branch BTW

**Comment by edgarf** [comment]
@regiscamimura this is really great! I'm just thinking, If the "default" language is going to be English. Then, to change a term, we would still need to go through every view file and change it?

**Comment by edgarf** [comment]
Hey @regiscamimura, tried to deploy your branch on my machine, please take a look below:

![screenshot_4](https://cloud.githubusercontent.com/assets/5213372/11713359/9fdc5134-9f3b-11e5-8fcf-e5acda53170b.png)

**Comment by regiscamimura** [comment]
This issue was caused by a problem with php short tags. I just implemented a fix that will make the translation mechanism to work on any environment and CodeIgniter config options. 
===
Currently, when english is the default language, you don't need to create the language entries (i.e., the ./application/language/english/easol_lang.php can be empty -- it must exists though), but you still need to go through the views and add double curly braces around any text. Also, when translating a single line, for example, when text is set on controllers, you need to use the <?php echo lang('some text'); ?>.

I could improve the translation mechanism so it would read the view as DOM, iterate over each text node and attempt the translation, so we won't even need the double curly braces, but that would reduce the system performance a little bit, it would not be 100% accurate, specially when we have concatenated translated text, or when the translated text is within some attribute, for example <a href="#" title="{{ text to be translated}}">{{link title}}</a>. 

It would be easier to put a script that read view files and automatically add the curly braces and then overwrite the current view file with the version using curly braces. It would not be 100% accurate yet, but it would be a big help to avoid manual work. Thoughts?
