### ISSUE TITLE
Percentage/Value Slider

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#308]
@regiscamimura, could you please investigate whether it's complicated to integrate percentage/value slider for Pie Chart reports? To understand what is the percentage value of each pie-slice.

**Comment by regiscamimura** [comment]
Just got it done. There are other format options, like using the tooltip for showing the percentage. What I did was to show the percentage value between brackets after the label, but let me know if you would like to have any other format.

**Comment by regiscamimura** [comment]
pushed to branch 266 btw

**Comment by edgarf** [comment]
@regiscamimura thanks! I, though, can't see the different (can you check on easol-dev? I deployed there). And also, from the files you commited, seems like you only added it for bar-charts? What about pie-chart?

**Comment by regiscamimura** [comment]
@edgarf actually, the change was only to pie-charts, not to bar-charts. If you tested it with bar charts, you wouldn't see any difference. Can you please try with pie charts?

Regarding bar chart implementation, I can get it done, but will need some more time cause bar chart doesn't have that config option, will need to implement our own function. Estimate is something between 2 and 4h. Anyway, as far as I understand, percentage values makes more sense to pie charts, since indeed each slice gets a fraction of the whole pie, while in the bar charts, each bar it's a single entity, they aren't actually a part of a whole, so we use absolute numbers to compare different scenarios. Thoughts?

**Comment by edgarf** [comment]
@regiscamimura, thank you. The charts were probably cached and I couldn't see the data. Now it's working. Let's wait with bar-charts for now.
