### ISSUE TITLE
Year filter drop-down values

### ISSUE THREAD

**Issue by edgarf** [EASOL/easol#329]
@regiscamimura, could you please review what are the **Year** values currently fed into that drop-downs on different listing views.

**Comment by regiscamimura** [comment]
@edgarf There are different methods for the year values:

- Students, Section, Attendance, Analytics: It list all years between the school configuration option for "CURRENT_SCHOOLYEAR" and the current year;
- Assessments: The options are extracted from the result set in the table

**Comment by edgarf** [comment]
@regiscamimura Thanks.

**Comment by edgarf** [comment]
@regiscamimura let's please just not forget about adding those 2 additional system variables (for current school year + term).

**Comment by edgarf** [comment]
Regis - would this be possible to also show options from the result for Students, Section, Attendance and Analytics? 
Also in Management -> School -> Edit. When configuring values. Where are thee years taken from?

Thanks!

**Comment by regiscamimura** [comment]
@edgarf I got it done for Students, Section, and Attendance, but for analytics, we'll need to think of a better solution. That's because we retrieve a chunk of data at a time, so we don't really know all the year options from the beginning. We can probably take advantage and find a better solution for the performance issues and API usage there, unless the API have a method to retrieve all possible years. Thoughts?

Regarding the management -> school -> edit section, the year options are hard-coded and limited to be 2010, 2011, 2012, and 2013. How would you want the options to be set?

**Comment by edgarf** [comment]
The best way is to only show those years, which are in the dataset. How much time would be needed to do that?

**Comment by regiscamimura** [comment]
@edgarf You mean show years in the dataset for the analytics? For all other views, it now show years in the dataset indeed, but for analytics we have a problem because we just get a small portion of the dataset at a time, so we don't really know what year options we're going to have. I'm not sure how we can retrieve all the possible years at once -- I actually do, but it would cause performance issues. Do we have any docs on the analytics API? I might find another method.

Other thing I can do is to add year options as the dataset loads, but be aware that we would be only be able to filter results that are already loaded, know what I mean?

Or do you mean you want the years option in management->school->edit section to somehow read from the database and get options from there?

**Comment by edgarf** [comment]
@regiscamimura - if it's already everywhere except the Analytics, then it's good enough already. Sorry for the confusion. That's already pushed?

**Comment by regiscamimura** [comment]
yes, already pushed
